# Example retry configuration file
# Place this file as .retry.toml in your project directory or home directory
# Or specify with --config flag
#
# Configuration precedence (highest to lowest):
# 1. CLI flags (--attempts, --delay, etc.)
# 2. Environment variables (RETRY_ATTEMPTS, RETRY_DELAY, etc.)
# 3. Configuration file values (this file)
# 4. Default values
#
# Environment variables:
# RETRY_ATTEMPTS, RETRY_DELAY, RETRY_TIMEOUT, RETRY_BACKOFF,
# RETRY_MAX_DELAY, RETRY_MULTIPLIER, RETRY_SUCCESS_PATTERN,
# RETRY_FAILURE_PATTERN, RETRY_CASE_INSENSITIVE

# Maximum number of retry attempts (default: 3)
attempts = 5

# Base delay between attempts (default: 0, no delay)
# Examples: "1s", "500ms", "2m"
delay = "1s"

# Timeout per attempt (default: 0, no timeout)
# Examples: "30s", "5m", "1h"
timeout = "30s"

# Backoff strategy: "fixed" or "exponential" (default: "fixed")
backoff = "exponential"

# Maximum delay for exponential backoff (default: 0, no limit)
# Only used when backoff = "exponential"
max_delay = "10s"

# Multiplier for exponential backoff (default: 2.0)
# Only used when backoff = "exponential"
multiplier = 2.0

# Regex pattern that indicates success in stdout/stderr
# If this pattern matches, the command is considered successful regardless of exit code
success_pattern = "deployment successful|build completed"

# Regex pattern that indicates failure in stdout/stderr
# If this pattern matches, the command is considered failed regardless of exit code
failure_pattern = "(?i)error|failed|timeout"

# Make pattern matching case-insensitive (default: false)
case_insensitive = true